// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'AtomsNcButton': typeof import('../components/atoms/NcButton.vue')['default'],
    'AtomsNcIcon': typeof import('../components/atoms/NcIcon.vue')['default'],
    'MoleculesNcLogo': typeof import('../components/molecules/NcLogo.vue')['default'],
    'PluginsHead': typeof import('../components/plugins/head.ts')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
